%-----------------------------ABSTRACT-----------------------------------
\section*{\centerline{Abstract} \centerline{} \centerline{Pyha - } \centerline{Object-Oriented Hardware Description Language}}

The task of implementing digital signal processing systems on hardware is often carried out by using high-level tools, such as MATLAB to HDL converter.  However, these tools can easily cost over tens of thousands of euros, making them unsuitable for reproducible research and open source designs. Other high-level tools are mostly based on 'C', which is not suitable for modeling and prototyping purposes.
Given the limitations and drawbacks of existing solutions,
this thesis proposes Pyha, a new Python based hardware description language aimed at simplifying DSP hardware
development in an open-source manner. Pyha raises the abstraction level by suggesting the object-oriented programming model and provides fixed-point type support.
In addition, this work makes an effort to simplify the testing process of hardware systems by
providing better simulation interface for unit-testing and debugging capabilities in Python domain.

The thesis is in English and contains 39 pages of text, 5 chapters, 24 figures.
\pagebreak