%---------------------------ANNOTATSIOON---------------------------------
\section*{\centerline{Annotatsioon}  \centerline{} \centerline{Pyha - } \centerline{Pythonil põninev objektorienteeritud riistvarakirjelduskeel}}

Digitaalse signaalitööstuse süsteemide riistvara loomiseks kasutatakse enamasti kõrgetasemelisi tööriistu, nagu näiteks 'MATLAB HDL Coder'. Need tööriistad pakuvad küll kõrget produktiivsust aga võivad maksta kümneid tuhandeid eurosid, mille tõttu pole need lahendused kasutatavad reprodutseeritava teadustöö ning avatud lähetkoodiga projektide jaoks. Enamus alternatiivseid lahendusi põhineb 'C' keelel, mis ei sobi modellerimiseks ega prototüüpimiseks. Vastavalt alternatiivse lahenduste puudustele, pakub see lõputöö välja Python programmeerimiskeelel põhineva riistvarakirjelduskeele, nimega Pyha, mille eesmärk on lihtsustada digitaalsete süsteemide arendamist. Lahendus põhineb avatud lähtekoodil. Pyha põnineb objektorienteeritud programmeerimisel ning toetab püsikomaarve. Lisaks on lihtsustatud riistvara testimimine, tänu lihtsustatud simulatsioonide jooksutamise liidesele, võimalik on Pythoni domeenis programmi silumine.


Lõputöö on kirjutatud inglise keeles ning sisaldab teksti 39 leheküljel, 5 peatükki, 24 joonist.
\pagebreak