%  Author’s declaration of originality
\restoregeometry %Taastab esialgsed lehesuuruse parameetrid
\footskip = 60pt
\section*{\centerline{Author’s declaration of originality}}
I hereby certify that I am the sole author of this thesis. All the used materials, references to the literature and the work of others have been referred to. This thesis has not been presented for examination anywhere else.

Author: {Gaspar Karm}\\
{[pp.kk.aaaa]}
\pagebreak