\begin{titlepage}%
   	
   	%\thispagestyle{fancy} %Võimaldab lihsalt timmida päist ja jalust
   	%\layout
   	\footskip = 60pt %Paneb paika jaluse kõrguse kogu dokumendi ulatuses, on sõltuvuses käsust /voffset
   	\renewcommand{\headrulewidth}{0pt} %Eemaldab päisest horisontaalse joone
   	%\renewcommand{\footrulewidth}{0pt} %Eemaldab jalusest %horisontaalse joone
   	\setlength{\voffset}{-20pt} %Tõstab teksti lehe üla servas kõrgemale headeri vaikimisi väärtusest (1 toll)
   	\begin{center}
   		\textsc{\begin{large} %Tekst suurtähtedega ja suuremaks
   				Tallinna Tehnikaülikool\\
   			\end{large} }
		 Infotehnoloogia teaduskond\\
		 {Thomas Johann Seebecki elektroonikainstituut} \\[4,7 cm]
   		\end{center}
   		
   		\begin{center} %Tekst keskele
   			{Gaspar Karm, IVEM153410}\\[2,3 cm]
   			\begin{huge}
   				
   				\textsc{\textbf{Pyha -  \\ Pythonil põninev Objektorienteeritud Riistvarakirjelduskeel \\[2,3 cm]}}
   			\end{huge}
   			{Magistritöö}\\[1,5 cm]
   		\end{center}
   		
   		\blank{10cm}
   		Juhendajad: %\blank{1cm}
   		\\[0cm]
   		%\begin{flushright} %Joondab teksti paremale
   		\blank{11.3 cm}{Muhammad Mahtab Alam}\\[0cm]
   		\blank{11.3 cm}{PhD}\\[0cm]
   		
   		\blank{11.3 cm}{Yannick Le Moullec}\\[0cm]
   		\blank{11.3 cm}{PhD}\\[0cm]
   		%\end{flushright}
   		

   		\blank{7.3 cm}{}\\[0cm]
   		\blank{7.3 cm}{}\\[0cm]
   		\blank{7.3 cm}{}\\[0cm]
   		\blank{7.3 cm}{}\\[0cm]
   		\blank{7.3 cm}{Tallinn 2017}\\[0cm]
   		
   	\end{titlepage}%