-- generated by pyha 0.0.4 at 2017-04-10 14:38:31
library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;
    use ieee.fixed_float_types.all;
    use ieee.fixed_pkg.all;
    use ieee.math_real.all;

library work;
    use work.ComplexTypes.all;
    use work.PyhaUtil.all;
    use work.all;


package MAC_0 is



    type next_t is record
        coef: integer;
        mul: integer;
        acc: integer;
    end record;

    type self_t is record

        coef: integer;
        mul: integer;
        acc: integer;
        \next\: next_t;
    end record;

    procedure \_pyha_init_self\(self: inout self_t);

    procedure \_pyha_constants_self\(self: inout self_t);

    procedure \_pyha_reset_self\(self: inout self_t);

    procedure \_pyha_update_self\(self: inout self_t);


    procedure main(self:inout self_t; a: integer; ret_0:out integer);
end package;

package body MAC_0 is
    procedure \_pyha_init_self\(self: inout self_t) is
    begin
        self.\next\.coef := self.coef;
        self.\next\.mul := self.mul;
        self.\next\.acc := self.acc;
        \_pyha_constants_self\(self);
    end procedure;

    procedure \_pyha_constants_self\(self: inout self_t) is
    begin


    end procedure;

    procedure \_pyha_reset_self\(self: inout self_t) is
    begin
        self.\next\.coef := 123;
        self.\next\.mul := 0;
        self.\next\.acc := 0;
        \_pyha_update_self\(self);
    end procedure;

    procedure \_pyha_update_self\(self: inout self_t) is
    begin
        self.coef := self.\next\.coef;
        self.mul := self.\next\.mul;
        self.acc := self.\next\.acc;
        \_pyha_constants_self\(self);
    end procedure;


    procedure main(self:inout self_t; a: integer; ret_0:out integer) is

    begin
        self.\next\.mul := self.coef * a;
        self.\next\.acc := self.acc + self.mul;
        ret_0 := self.acc;
        return;

    end procedure;
end package body;
