-- generated by pyha 0.0.4 at 2017-04-10 14:38:31
library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;
    use ieee.fixed_float_types.all;
    use ieee.fixed_pkg.all;
    use ieee.math_real.all;

library work;
    use work.ComplexTypes.all;
    use work.PyhaUtil.all;
    use work.all;


package ReuseParallel_0 is



    type next_t is record
        mac0: MAC_0.self_t;
        mac1: MAC_1.self_t;
    end record;

    type self_t is record

        mac0: MAC_0.self_t;
        mac1: MAC_1.self_t;
        \next\: next_t;
    end record;

    procedure \_pyha_init_self\(self: inout self_t);

    procedure \_pyha_constants_self\(self: inout self_t);

    procedure \_pyha_reset_self\(self: inout self_t);

    procedure \_pyha_update_self\(self: inout self_t);


    procedure main(self:inout self_t; a: integer; ret_0:out integer; ret_1:out integer);
end package;

package body ReuseParallel_0 is
    procedure \_pyha_init_self\(self: inout self_t) is
    begin
        MAC_0.\_pyha_init_self\(self.mac0);
        MAC_1.\_pyha_init_self\(self.mac1);
        \_pyha_constants_self\(self);
    end procedure;

    procedure \_pyha_constants_self\(self: inout self_t) is
    begin

        MAC_0.\_pyha_constants_self\(self.mac0);
        MAC_1.\_pyha_constants_self\(self.mac1);
    end procedure;

    procedure \_pyha_reset_self\(self: inout self_t) is
    begin
        MAC_0.\_pyha_reset_self\(self.mac0);
        MAC_1.\_pyha_reset_self\(self.mac1);
        \_pyha_update_self\(self);
    end procedure;

    procedure \_pyha_update_self\(self: inout self_t) is
    begin
        MAC_0.\_pyha_update_self\(self.mac0);
        MAC_1.\_pyha_update_self\(self.mac1);
        \_pyha_constants_self\(self);
    end procedure;


    procedure main(self:inout self_t; a: integer; ret_0:out integer; ret_1:out integer) is
        variable out0: integer;
        variable out1: integer;
    begin
        MAC_0.main(self.mac0, a, ret_0=>out0);
        MAC_1.main(self.mac1, a, ret_0=>out1);
        ret_0 := out0;
        ret_1 := out1;
        return;
    end procedure;
end package body;
