-- generated by pyha 0.0.4 at 2017-04-21 19:40:17
library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;
    use ieee.fixed_float_types.all;
    use ieee.fixed_pkg.all;
    use ieee.math_real.all;

library work;
    use work.ComplexTypes.all;
    use work.PyhaUtil.all;
    use work.all;


package LastAcc_0 is

    type integer_list_t is array (natural range <>) of integer;

    type next_t is record
        shr: integer_list_t(0 to 3);
        y: integer;
    end record;

    type self_t is record
        -- constants
        \_delay\: integer;

        shr: integer_list_t(0 to 3);
        y: integer;
        \next\: next_t;
    end record;

    procedure \_pyha_init_self\(self: inout self_t);

    procedure \_pyha_constants_self\(self: inout self_t);

    procedure \_pyha_reset_self\(self: inout self_t);

    procedure \_pyha_update_self\(self: inout self_t);


    procedure main(self:inout self_t; x: integer; ret_0:out integer);
end package;

package body LastAcc_0 is
    procedure \_pyha_init_self\(self: inout self_t) is
    begin
        self.\next\.shr := self.shr;
        self.\next\.y := self.y;
        \_pyha_constants_self\(self);
    end procedure;

    procedure \_pyha_constants_self\(self: inout self_t) is
    begin
        self.\_delay\ := 2;

    end procedure;

    procedure \_pyha_reset_self\(self: inout self_t) is
    begin
        self.\next\.shr := (0, 0, 0, 0);
        self.\next\.y := 0;
        \_pyha_update_self\(self);
    end procedure;

    procedure \_pyha_update_self\(self: inout self_t) is
    begin
        self.shr := self.\next\.shr;
        self.y := self.\next\.y;
        \_pyha_constants_self\(self);
    end procedure;


    procedure main(self:inout self_t; x: integer; ret_0:out integer) is
        variable sum: integer;
    begin
        -- add new element to shift register
        self.\next\.shr := x & self.shr(0 to self.shr'high-1);

        sum := 0;
        for \_i_\ in self.shr'range loop
            sum := sum + self.shr(\_i_\);

        end loop;
        self.\next\.y := sum;
        ret_0 := self.y;
        return;
    end procedure;
end package body;
