-- generated by pyha 0.0.4 at 2017-04-18 15:37:48
library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;
    use ieee.fixed_float_types.all;
    use ieee.fixed_pkg.all;
    use ieee.math_real.all;

library work;
    use work.ComplexTypes.all;
    use work.PyhaUtil.all;
    use work.all;


package MAC_seq_0 is



    type next_t is record
        coef: integer;
        y: integer;
    end record;

    type self_t is record
        -- constants
        \_delay\: integer;

        coef: integer;
        y: integer;
        \next\: next_t;
    end record;

    procedure \_pyha_init_self\(self: inout self_t);

    procedure \_pyha_constants_self\(self: inout self_t);

    procedure \_pyha_reset_self\(self: inout self_t);

    procedure \_pyha_update_self\(self: inout self_t);


    procedure main(self:inout self_t; a: integer; sum_in: integer; ret_0:out integer);
end package;

package body MAC_seq_0 is
    procedure \_pyha_init_self\(self: inout self_t) is
    begin
        self.\next\.coef := self.coef;
        self.\next\.y := self.y;
        \_pyha_constants_self\(self);
    end procedure;

    procedure \_pyha_constants_self\(self: inout self_t) is
    begin
        self.\_delay\ := 1;

    end procedure;

    procedure \_pyha_reset_self\(self: inout self_t) is
    begin
        self.\next\.coef := 9;
        self.\next\.y := 0;
        \_pyha_update_self\(self);
    end procedure;

    procedure \_pyha_update_self\(self: inout self_t) is
    begin
        self.coef := self.\next\.coef;
        self.y := self.\next\.y;
        \_pyha_constants_self\(self);
    end procedure;


    procedure main(self:inout self_t; a: integer; sum_in: integer; ret_0:out integer) is
        variable mul: integer;
    begin
        mul := self.coef * a;
        self.\next\.y := sum_in + mul;
        ret_0 := self.y;
        return;
    end procedure;
end package body;
